# Generated by Django 5.2.9 on 2025-12-05 13:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('supplier_code', models.CharField(help_text='Unique code for the supplier', max_length=50, unique=True, verbose_name='Supplier Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Supplier rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('blacklisted', 'Blacklisted')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('name', models.CharField(help_text='Full name of the unit (e.g., Kilograms)', max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters'), ('m', 'Meters'), ('cm', 'Centimeters'), ('box', 'Box'), ('pack', 'Pack'), ('set', 'Set')], help_text='Unit symbol (e.g., kg)', max_length=20, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('code', models.CharField(help_text='Unique code for the product group', max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent_group', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_groups', to='products.productgroup', verbose_name='Parent Group')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('product_code', models.CharField(help_text='Unique product identifier', max_length=50, unique=True, verbose_name='Product Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('generic_name', models.CharField(blank=True, max_length=200, verbose_name='Generic Name')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Short Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System code for customs', max_length=50, verbose_name='HS Code')),
                ('is_batch_tracked', models.BooleanField(default=False, help_text='Whether this product is tracked by batch number', verbose_name='Batch Tracked')),
                ('is_serial_tracked', models.BooleanField(default=False, help_text='Whether this product is tracked by serial number', verbose_name='Serial Tracked')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Buy Price')),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='MRP')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cost Price')),
                ('quantity', models.IntegerField(default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Quantity')),
                ('min_quantity', models.IntegerField(default=10, help_text='Minimum stock level before reorder', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Quantity')),
                ('max_quantity', models.IntegerField(default=100, help_text='Maximum stock level', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Quantity')),
                ('product_type_category', models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Goods'), ('IH', 'In-House'), ('FF', 'Finished Feed')], help_text='Product category type (RM, FG, IH, FF)', max_length=2, verbose_name='Product Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('discontinued', 'Discontinued')], default='active', max_length=20, verbose_name='Status')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productgroup', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_code'],
            },
        ),
    ]
