# Generated by Django 5.2.9 on 2025-12-05 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AddIndex(
            model_name='productmaster',
            index=models.Index(fields=['product_code'], name='products_pr_product_c3833d_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaster',
            index=models.Index(fields=['product_type_category'], name='products_pr_product_ca216f_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaster',
            index=models.Index(fields=['status'], name='products_pr_status_f3b13a_idx'),
        ),
    ]
