# Generated by Django 5.2.9 on 2025-12-05 13:11

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('batch_number', models.CharField(help_text='Batch or lot number of the sample', max_length=100, verbose_name='Batch Number')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Status')),
                ('sample_date', models.DateField(help_text='Date when the sample was received', verbose_name='Sample Date')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or comments', verbose_name='Remarks')),
                ('current_step', models.IntegerField(default=1, help_text='Current step in the testing pipeline (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Current Step')),
            ],
            options={
                'verbose_name': 'Test Request',
                'verbose_name_plural': 'Test Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('actual_value', models.CharField(help_text='Actual test result value (can be numeric, text, or boolean)', max_length=200, verbose_name='Actual Value')),
                ('pass_fail_status', models.BooleanField(blank=True, help_text='True if test passed, False if failed, None if not yet calculated', null=True, verbose_name='Pass/Fail Status')),
                ('tested_at', models.DateTimeField(auto_now_add=True, verbose_name='Tested At')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
                'ordering': ['test_request', 'parameter'],
            },
        ),
    ]
