# Generated by Django 5.2.9 on 2025-12-05 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('quality', '0002_initial'),
        ('testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='controller_user',
            field=models.ForeignKey(help_text='User responsible for this test', on_delete=django.db.models.deletion.PROTECT, related_name='test_requests', to=settings.AUTH_USER_MODEL, verbose_name='Controller'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_requests', to='products.productmaster', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_requests', to='products.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_results', to='quality.testparameter', verbose_name='Test Parameter'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testing.testrequest', verbose_name='Test Request'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Tested By'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['batch_number'], name='testing_tes_batch_n_193b46_idx'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['status'], name='testing_tes_status_24b385_idx'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['sample_date'], name='testing_tes_sample__a1cba0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('test_request', 'parameter')},
        ),
    ]
