# Generated by Django 5.2.9 on 2025-12-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Submitted for Review', 'Submitted for Review'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
