# Generated by Django 5.2.9 on 2025-12-05 13:11

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('target_value', models.CharField(blank=True, help_text='Target or expected value for this parameter', max_length=100, verbose_name='Target Value')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum acceptable value (for numeric parameters)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Minimum Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum acceptable value (for numeric parameters)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximum Value')),
                ('min_limit', models.CharField(blank=True, help_text='Minimum limit (for text parameters)', max_length=100, verbose_name='Minimum Limit')),
                ('max_limit', models.CharField(blank=True, help_text='Maximum limit (for text parameters)', max_length=100, verbose_name='Maximum Limit')),
                ('standard_text_value', models.CharField(blank=True, help_text='Standard value for text or boolean parameters', max_length=200, verbose_name='Standard Text Value')),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., %, ppm, mg/kg)', max_length=50, verbose_name='Unit')),
                ('test_method', models.CharField(blank=True, help_text='Method used to test this parameter', max_length=200, verbose_name='Test Method')),
                ('is_critical', models.BooleanField(default=False, help_text='Whether this is a critical parameter that must pass', verbose_name='Critical Parameter')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'ordering': ['product', 'parameter'],
            },
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('name', models.CharField(help_text='Name of the test parameter (e.g., Moisture, Ash%, Aflatoxin)', max_length=200, unique=True, verbose_name='Parameter Name')),
                ('data_type', models.CharField(choices=[('Numeric', 'Numeric'), ('Text', 'Text'), ('Boolean', 'Boolean')], default='Numeric', help_text='Type of data this parameter accepts', max_length=20, verbose_name='Data Type')),
            ],
            options={
                'verbose_name': 'Test Parameter',
                'verbose_name_plural': 'Test Parameters',
                'ordering': ['name'],
            },
        ),
    ]
