# Generated by Django 5.2.9 on 2025-12-07 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active. Unselect this instead of deleting.', verbose_name='Is Active')),
                ('code', models.CharField(help_text='Short code for the test method (e.g., ISO6579, AOAC920.87)', max_length=50, unique=True, verbose_name='Method Code')),
                ('name', models.CharField(help_text='Full name of the test method', max_length=200, verbose_name='Method Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the test method', verbose_name='Description')),
                ('standard_organization', models.CharField(blank=True, help_text='Organization that published the standard (e.g., ISO, AOAC, ASTM)', max_length=100, verbose_name='Standard Organization')),
            ],
            options={
                'verbose_name': 'Test Method',
                'verbose_name_plural': 'Test Methods',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='test_method',
            field=models.ForeignKey(blank=True, help_text='Standard method used to test this parameter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to='quality.testmethod', verbose_name='Test Method'),
        ),
    ]
